[agent]
  interval = "10s"
  flush_interval = "10s"
  omit_hostname = false

[[inputs.mqtt_consumer]]
  servers = ["tcp://core-mosquitto:1883"]
  username = "mqtt user"
  password = "mqtt password"
  
  topics = [
    "Jikong_BMS/+/realtime",
    "Jikong_BMS/+/settings"
  ]
  data_format = "json"
  name_override = "jikong_bms"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "Jikong_BMS/+/+"
    tags = "_/device_id/msg_type"

  # 👇 核心白名單：全面切換為英文 Key (對應 bms_registers.py 的 entry[6])
  fieldpass = [
    "current",              # 电池电流
    "total_voltage",        # 电池总电压
    "max_diff_voltage",     # 最大压差
    "temp_sensor_*",        # 電池溫度 1~5
    "power_board_temp"      # 功率板温度
  ]

  # 👇 擊殺 UID 15 的黑名單不變
  [inputs.mqtt_consumer.tagdrop]
    device_id = ["15"]

[[outputs.influxdb_v2]]
  urls = ["http://192.168.106.32:8086"]  # 填入實際 IP
  token = "ig-super-token"
  organization = "ig-org"
  bucket = "irongate"

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
