app:
  debug_raw_log: false
  packet_expire_time: 2.0
  settings_publish_interval: 60
  use_modbus_gateway: false
  use_rs485_usb: true
mqtt:
  client_id: jk_bms_monitor
  discovery_prefix: homeassistant
  host: 192.168.106.5
  password: mqtt
  port: 1883
  topic_prefix: Jikong_BMS
  username: mqtt
serial:
  baudrate: 115200
  device: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  timeout: 1.0
tcp:
  buffer_size: 4096
  host: 192.168.106.5
  port: 502
  timeout: 10
